# Generated by Django 3.0.5 on 2020-06-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address_2',
        ),
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.CharField(max_length=2000, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='organization',
            name='emp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Orgsocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked', models.URLField(blank=True, null=True)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'verbose_name': 'Organization Social Accounts',
            },
        ),
        migrations.CreateModel(
            name='Orgphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='comp_gallery')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'verbose_name': 'Organization Photo',
                'verbose_name_plural': 'Organization Gallery',
            },
        ),
    ]
