# Generated by Django 2.2.2 on 2020-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='contractType',
            field=models.CharField(choices=[('0', 'Contract'), ('1', 'Internship'), ('2', 'Temporary'), ('3', 'Walk-In'), ('4', 'Fresher')], default='Fresher', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hear',
            field=models.CharField(choices=[('0', 'Mail'), ('1', 'Tv'), ('2', 'Newspapaer'), ('3', 'other')], default='Newspaper', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[('0', 'Full time'), ('1', 'Part time')], default='Full time', max_length=20),
        ),
    ]
