# Generated by Django 2.2.2 on 2020-07-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200703_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='edu',
            new_name='education_details',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='prevEmp',
            new_name='prev_Employments',
        ),
    ]
