# Generated by Django 2.2.2 on 2020-07-04 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200703_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_emp', models.BooleanField(default=False)),
                ('is_seek', models.BooleanField(default=False)),
                ('skills', models.CharField(help_text='Mention Your Skils', max_length=255, null=True)),
                ('experience', models.CharField(max_length=255, null=True, verbose_name='experience')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('prev_Employments', models.CharField(help_text='Mention Your Previous employments', max_length=255, null=True)),
                ('education_details', models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details')),
                ('projects', models.CharField(max_length=255, null=True, verbose_name='Give a beief about your projects')),
                ('accomplishments', models.CharField(max_length=255, null=True, verbose_name='accomplishments')),
                ('otherLinks', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
            },
        ),
    ]
