# Generated by Django 2.2.2 on 2020-07-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobpost'),
        ),
    ]
