# Generated by Django 2.2.2 on 2020-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_applicant_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='education_details',
            new_name='bachelor_degree',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='otherLinks',
            new_name='codechef',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CGPA_For_bachelors',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CGPA_For_masters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackkerank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='masters_degree',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenth_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twelth_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yop_for_bachelors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yop_for_masters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yop_for_tenth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yop_for_twelfth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
