# Generated by Django 2.2.2 on 2020-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200706_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='CGPA_For_bachelors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CGPA_For_masters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
