# Generated by Django 2.2.2 on 2020-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200706_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='CGPA_For_bachelors',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CGPA_For_masters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
