# Generated by Django 3.0.5 on 2020-06-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200613_1221'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(blank=True, max_length=300, null=True)),
                ('Exp', models.IntegerField(default=0)),
                ('Salary', models.IntegerField(default=0)),
                ('Salary_Type', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day'), ('Hour', 'Hour'), ('Project', 'Project')], default='Year', max_length=100)),
                ('Salary_Currency', models.CharField(default='INR', max_length=20)),
                ('NOO', models.IntegerField(default=1)),
                ('Qualification', models.CharField(blank=True, max_length=400, null=True)),
                ('Shift', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=2000, null=True)),
                ('Category', models.CharField(default='Other', max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Imp', models.CharField(choices=[('Featured', 'Featured'), ('Urgent', 'Urgent'), ('Private', 'Private')], default='Private', max_length=100)),
                ('Posted', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Closed', 'Closed')], default='Draft', max_length=100)),
                ('Type', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], default='Full Time', max_length=150)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.OrganizationAdmin')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Jobskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Skill')),
            ],
        ),
    ]
